In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [33]:
columns = ["lettr", "x-box", "y-box", "width", "height", "onpix", "x-bar","y-bar", "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege", "xegvy", "y-ege", "yegvx"]

In [34]:
df = pd.read_csv('2_letter_recognition.data', names=columns)

In [35]:
df.shape

(20000, 17)

In [36]:
df.head

<bound method NDFrame.head of       lettr  x-box  y-box  width  height  onpix  x-bar  y-bar  x2bar  y2bar  \
0         T      2      8      3       5      1      8     13      0      6   
1         I      5     12      3       7      2     10      5      5      4   
2         D      4     11      6       8      6     10      6      2      6   
3         N      7     11      6       6      3      5      9      4      6   
4         G      2      1      3       1      1      8      6      6      6   
...     ...    ...    ...    ...     ...    ...    ...    ...    ...    ...   
19995     D      2      2      3       3      2      7      7      7      6   
19996     C      7     10      8       8      4      4      8      6      9   
19997     T      6      9      6       7      5      6     11      3      7   
19998     S      2      3      4       2      1      8      7      2      6   
19999     A      4      9      6       6      2      9      5      3      1   

       xybar  x2ybr  

In [37]:
#Displaying particular row from df
df.loc[[4],:]

lettr  x-box  y-box  width  height  onpix  x-bar  y-bar  x2bar  y2bar  \
4     G      2      1      3       1      1      8      6      6      6   

   xybar  x2ybr  xy2br  x-ege  xegvy  y-ege  yegvx  
4      6      5      9      1      7      5     10

In [38]:
x = df.drop("lettr", axis=1).values
y = df["lettr"].values

In [39]:
#Accessing single row of x using np.array
print(x[1])
x.shape

[ 5 12  3  7  2 10  5  5  4 13  3  9  2  8  4 10]


(20000, 16)

In [40]:
#Printing output(y) of corresponding input(x)
print(y[1])
y.shape

I


(20000,)

In [41]:
np.unique(y)

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype=object)

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [43]:
x_train[0]

array([ 5,  9,  7,  6,  6,  5, 10,  5,  5, 10,  8,  3,  1, 10,  3,  7],
      dtype=int64)

In [44]:
def shape():
  print("Train Shape :",x_train.shape)
  print("Test Shape :",x_test.shape)
  print("y_train shape :",y_train.shape)
  print("y_test shape :",y_test.shape)
shape()

Train Shape : (16000, 16)
Test Shape : (4000, 16)
y_train shape : (16000,)
y_test shape : (4000,)


In [45]:
x_train[1]

array([ 3,  7,  4,  4,  2,  5, 11,  8,  3,  7,  3,  9,  3,  7,  5, 11],
      dtype=int64)

In [46]:
y_test[1]

'A'

In [47]:
class_names=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

**Preprocessing**

In [48]:
x_train = x_train/255
x_test = x_test/255

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)
a = encoder.fit_transform(y_train)
b = encoder.fit_transform(y_test)

In [51]:
np.unique(y_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [52]:
np.unique(y_test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

**Building our Model**

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [54]:
model=Sequential()

In [55]:
model.add(Dense(512, activation='relu', input_shape=(16,)))
model.add(Dropout(0.2))

C:\Users\Ashish\anaconda3\envs\new\lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [56]:
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))

In [57]:
model.add(Dense(26, activation='softmax'))

In [58]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [59]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 512)                 │           8,704 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 26)                  │           6,682 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 146,714 (573.10 KB)

 Trainable params: 146,714 (573.10 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.fit(x_train, y_train, epochs=50, batch_size=128, verbose=1,validation_data=(x_test, y_test))

Epoch 1/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1041 - loss: 3.2182 - val_accuracy: 0.2150 - val_loss: 2.7284
Epoch 2/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2767 - loss: 2.5155 - val_accuracy: 0.3955 - val_loss: 2.0736
Epoch 3/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.3971 - loss: 2.0172 - val_accuracy: 0.4750 - val_loss: 1.8504
Epoch 4/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4645 - loss: 1.7912 - val_accuracy: 0.5157 - val_loss: 1.6518
Epoch 5/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5071 - loss: 1.6282 - val_accuracy: 0.5435 - val_loss: 1.5421
Epoch 6/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5370 - loss: 1.5302 - val_accuracy: 0.5867 - val_loss: 1.4481
Epoch 7/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5619 - loss: 1.4450 - val_accuracy: 0.5893 - val_loss: 1.3978
Epoch 8/50
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5837 - loss: 1.3878 - val_accuracy: 0.

**Testing our Model**

In [61]:
predictions = model.predict(x_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [62]:
index=9
print(predictions[index])
final_value=np.argmax(predictions[index])
print("Actual label :",y_test[index])
print("Predicted label :",final_value)
print("Class (A-Z) :",class_names[final_value])

[1.4173976e-06 5.2308602e-22 4.5125109e-10 8.2859956e-15 4.1742515e-17
 6.6239441e-09 3.8841458e-15 1.7407354e-08 1.4359233e-09 2.4317320e-10
 5.7693228e-10 1.6642386e-10 1.3511279e-11 9.6698823e-06 4.0647352e-13
 3.3601172e-10 1.6444607e-10 1.3373135e-19 6.5202101e-11 4.2711807e-05
 3.2973196e-04 9.8121578e-01 1.6728937e-04 1.5152732e-06 1.8231900e-02
 1.1717206e-24]
Actual label : 21
Predicted label : 21
Class (A-Z) : V
